/**
 * STruC++ Code Generator
 *
 * Generates C++ code from the typed AST or IR.
 * Produces readable, debuggable C++ that maintains line correspondence with ST source.
 */

import type { CompilationUnit } from '../frontend/ast.js';
import type { SymbolTables } from '../semantic/symbol-table.js';
import type { LineMapEntry } from '../types.js';

// =============================================================================
// Code Generation Options
// =============================================================================

/**
 * Options for code generation.
 */
export interface CodeGenOptions {
  /** Include #line directives for debugging */
  lineDirectives: boolean;

  /** Include ST source as comments */
  sourceComments: boolean;

  /** Indentation string (default: 4 spaces) */
  indent: string;

  /** Line ending (default: \n) */
  lineEnding: string;
}

/**
 * Default code generation options.
 */
export const defaultCodeGenOptions: CodeGenOptions = {
  lineDirectives: false,
  sourceComments: true,
  indent: '    ',
  lineEnding: '\n',
};

// =============================================================================
// Code Generation Result
// =============================================================================

/**
 * Result of code generation.
 */
export interface CodeGenResult {
  /** Generated C++ implementation code */
  cppCode: string;

  /** Generated C++ header code */
  headerCode: string;

  /** Line mapping from ST to C++ */
  lineMap: Map<number, LineMapEntry>;
}

// =============================================================================
// Code Generator
// =============================================================================

/**
 * C++ code generator for IEC 61131-3 programs.
 */
export class CodeGenerator {
  private options: CodeGenOptions;
  private output: string[] = [];
  private headerOutput: string[] = [];
  private lineMap: Map<number, LineMapEntry> = new Map();
  private currentLine = 1;
  private indentLevel = 0;

  constructor(
    private readonly _symbolTables: SymbolTables,
    options: Partial<CodeGenOptions> = {}
  ) {
    this.options = { ...defaultCodeGenOptions, ...options };
  }

  /** Get symbol tables (for future use in Phase 3+) */
  get symbolTables(): SymbolTables {
    return this._symbolTables;
  }

  /**
   * Generate C++ code from a compilation unit.
   */
  generate(ast: CompilationUnit): CodeGenResult {
    this.output = [];
    this.headerOutput = [];
    this.lineMap = new Map();
    this.currentLine = 1;
    this.indentLevel = 0;

    // Generate header
    this.generateHeader(ast);

    // Generate implementation
    this.generateImplementation(ast);

    return {
      cppCode: this.output.join(this.options.lineEnding),
      headerCode: this.headerOutput.join(this.options.lineEnding),
      lineMap: this.lineMap,
    };
  }

  /**
   * Generate the C++ header file.
   */
  private generateHeader(ast: CompilationUnit): void {
    this.emitHeader('#pragma once');
    this.emitHeader('');
    this.emitHeader('// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler');
    this.emitHeader('// Do not edit this file manually.');
    this.emitHeader('');
    this.emitHeader('#include "iec_types.hpp"');
    this.emitHeader('#include "iec_std_lib.hpp"');
    this.emitHeader('');

    // Generate forward declarations
    for (const fb of ast.functionBlocks) {
      this.emitHeader(`class ${fb.name};`);
    }
    if (ast.functionBlocks.length > 0) {
      this.emitHeader('');
    }

    // Generate function block class declarations
    for (const fb of ast.functionBlocks) {
      this.generateFBHeaderDeclaration(fb);
    }

    // Generate program class declarations
    for (const prog of ast.programs) {
      this.generateProgramHeaderDeclaration(prog);
    }

    // Generate function declarations
    for (const func of ast.functions) {
      this.generateFunctionHeaderDeclaration(func);
    }
  }

  /**
   * Generate the C++ implementation file.
   */
  private generateImplementation(ast: CompilationUnit): void {
    this.emit('// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler');
    this.emit('// Do not edit this file manually.');
    this.emit('');
    this.emit('#include "generated.hpp"');
    this.emit('');

    // TODO: Generate actual implementation in Phase 3+
    // For now, generate placeholder implementations

    for (const prog of ast.programs) {
      this.generateProgramImplementation(prog);
    }

    for (const fb of ast.functionBlocks) {
      this.generateFBImplementation(fb);
    }

    for (const func of ast.functions) {
      this.generateFunctionImplementation(func);
    }
  }

  /**
   * Generate header declaration for a function block.
   */
  private generateFBHeaderDeclaration(
    fb: CompilationUnit['functionBlocks'][0]
  ): void {
    this.emitHeader(`class ${fb.name} {`);
    this.emitHeader('public:');

    // Generate member variables
    for (const block of fb.varBlocks) {
      const comment =
        block.blockType === 'VAR_INPUT'
          ? '// Inputs'
          : block.blockType === 'VAR_OUTPUT'
            ? '// Outputs'
            : block.blockType === 'VAR_IN_OUT'
              ? '// In-Out'
              : '// Local variables';

      this.emitHeader(`    ${comment}`);
      for (const decl of block.declarations) {
        for (const name of decl.names) {
          this.emitHeader(`    IEC_${decl.type.name} ${name};`);
        }
      }
    }

    this.emitHeader('');
    this.emitHeader('    // Constructor');
    this.emitHeader(`    ${fb.name}();`);
    this.emitHeader('');
    this.emitHeader('    // Execute function block');
    this.emitHeader('    void operator()();');
    this.emitHeader('};');
    this.emitHeader('');
  }

  /**
   * Generate header declaration for a program.
   */
  private generateProgramHeaderDeclaration(
    prog: CompilationUnit['programs'][0]
  ): void {
    this.emitHeader(`class Program_${prog.name} : public ProgramBase {`);
    this.emitHeader('public:');

    // Generate member variables
    for (const block of prog.varBlocks) {
      for (const decl of block.declarations) {
        for (const name of decl.names) {
          this.emitHeader(`    IEC_${decl.type.name} ${name};`);
        }
      }
    }

    this.emitHeader('');
    this.emitHeader('    // Constructor');
    this.emitHeader(`    Program_${prog.name}();`);
    this.emitHeader('');
    this.emitHeader('    // Run program');
    this.emitHeader('    void run() override;');
    this.emitHeader('};');
    this.emitHeader('');
  }

  /**
   * Generate header declaration for a function.
   */
  private generateFunctionHeaderDeclaration(
    func: CompilationUnit['functions'][0]
  ): void {
    const params: string[] = [];
    for (const block of func.varBlocks) {
      if (block.blockType === 'VAR_INPUT') {
        for (const decl of block.declarations) {
          for (const name of decl.names) {
            params.push(`IEC_${decl.type.name} ${name}`);
          }
        }
      }
    }

    this.emitHeader(
      `IEC_${func.returnType.name} ${func.name}(${params.join(', ')});`
    );
  }

  /**
   * Generate implementation for a program.
   */
  private generateProgramImplementation(
    prog: CompilationUnit['programs'][0]
  ): void {
    // Constructor
    this.emit(`Program_${prog.name}::Program_${prog.name}() {`);
    this.emit('    // Initialize variables');
    for (const block of prog.varBlocks) {
      for (const decl of block.declarations) {
        if (decl.initialValue !== undefined) {
          for (const name of decl.names) {
            // TODO: Generate proper initialization in Phase 3+
            this.emit(`    // ${name} = <initial value>;`);
          }
        }
      }
    }
    this.emit('}');
    this.emit('');

    // Run method
    this.emit(`void Program_${prog.name}::run() {`);
    if (this.options.sourceComments) {
      this.emit('    // TODO: Implement program body (Phase 3+)');
    }
    // TODO: Generate actual body in Phase 3+
    this.emit('}');
    this.emit('');
  }

  /**
   * Generate implementation for a function block.
   */
  private generateFBImplementation(
    fb: CompilationUnit['functionBlocks'][0]
  ): void {
    // Constructor
    this.emit(`${fb.name}::${fb.name}() {`);
    this.emit('    // Initialize variables');
    this.emit('}');
    this.emit('');

    // Operator()
    this.emit(`void ${fb.name}::operator()() {`);
    if (this.options.sourceComments) {
      this.emit('    // TODO: Implement function block body (Phase 3+)');
    }
    this.emit('}');
    this.emit('');
  }

  /**
   * Generate implementation for a function.
   */
  private generateFunctionImplementation(
    func: CompilationUnit['functions'][0]
  ): void {
    const params: string[] = [];
    for (const block of func.varBlocks) {
      if (block.blockType === 'VAR_INPUT') {
        for (const decl of block.declarations) {
          for (const name of decl.names) {
            params.push(`IEC_${decl.type.name} ${name}`);
          }
        }
      }
    }

    this.emit(
      `IEC_${func.returnType.name} ${func.name}(${params.join(', ')}) {`
    );
    this.emit(`    IEC_${func.returnType.name} ${func.name}_result;`);
    if (this.options.sourceComments) {
      this.emit('    // TODO: Implement function body (Phase 3+)');
    }
    this.emit(`    return ${func.name}_result;`);
    this.emit('}');
    this.emit('');
  }

  /**
   * Emit a line to the implementation output.
   */
  private emit(line: string): void {
    this.output.push(line);
    this.currentLine++;
  }

  /**
   * Emit a line to the header output.
   */
  private emitHeader(line: string): void {
    this.headerOutput.push(line);
  }

  /**
   * Get the current indentation string.
   * Used in Phase 3+ for proper code formatting.
   */
  protected getIndent(): string {
    return this.options.indent.repeat(this.indentLevel);
  }

  /**
   * Increase indentation level.
   * Used in Phase 3+ for proper code formatting.
   */
  protected indent(): void {
    this.indentLevel++;
  }

  /**
   * Decrease indentation level.
   * Used in Phase 3+ for proper code formatting.
   */
  protected dedent(): void {
    if (this.indentLevel > 0) {
      this.indentLevel--;
    }
  }

  /**
   * Record a line mapping from ST to C++.
   * Used in Phase 3+ for debugging support.
   */
  protected recordLineMapping(stLine: number, cppStartLine: number): void {
    const existing = this.lineMap.get(stLine);
    if (existing !== undefined) {
      existing.cppEndLine = this.currentLine;
    } else {
      this.lineMap.set(stLine, {
        cppStartLine,
        cppEndLine: this.currentLine,
      });
    }
  }
}

/**
 * Generate C++ code from a compilation unit.
 * Convenience function that creates a generator and runs code generation.
 */
export function generateCode(
  ast: CompilationUnit,
  symbolTables: SymbolTables,
  options?: Partial<CodeGenOptions>
): CodeGenResult {
  const generator = new CodeGenerator(symbolTables, options);
  return generator.generate(ast);
}
