// SPDX-License-Identifier: GPL-3.0-or-later WITH STruCpp-runtime-exception
// Copyright (C) 2025 Autonomy / OpenPLC Project
// This file is part of the STruC++ Runtime Library and is covered by the
// STruC++ Runtime Library Exception. See COPYING.RUNTIME for details.
/**
 * STruC++ Runtime - IEC Enumeration Support
 *
 * This header provides infrastructure for IEC 61131-3 enumeration types.
 * Enumerations in IEC 61131-3 are strongly typed, similar to C++ enum class.
 * Actual enum definitions are generated by the compiler based on user TYPE declarations.
 */

#pragma once

#include <cstdint>
#ifndef __AVR__
#include <ostream>
#endif
#include <type_traits>
#include "iec_var.hpp"

namespace strucpp {

/**
 * Value wrapper for IEC enumerations.
 * Provides a type-safe wrapper around C++ enum class types.
 *
 * @tparam EnumType The underlying C++ enum class type
 */
template<typename EnumType>
class IEC_ENUM_Value {
private:
    EnumType value_;
    
public:
    using enum_type = EnumType;
    
    // Default constructor - initializes to first enum value (0)
    constexpr IEC_ENUM_Value() noexcept : value_{} {}
    
    // Constructor from enum value
    constexpr IEC_ENUM_Value(EnumType val) noexcept : value_(val) {}
    
    // Implicit conversion to underlying enum
    constexpr operator EnumType() const noexcept { return value_; }
    
    // Get the underlying enum value
    constexpr EnumType get() const noexcept { return value_; }
    
    // Assignment from enum value
    IEC_ENUM_Value& operator=(EnumType val) noexcept {
        value_ = val;
        return *this;
    }
    
    // Comparison operators
    constexpr bool operator==(const IEC_ENUM_Value& other) const noexcept {
        return value_ == other.value_;
    }
    
    constexpr bool operator!=(const IEC_ENUM_Value& other) const noexcept {
        return value_ != other.value_;
    }
    
    constexpr bool operator==(EnumType val) const noexcept {
        return value_ == val;
    }
    
    constexpr bool operator!=(EnumType val) const noexcept {
        return value_ != val;
    }
    
    // Ordering operators (for enums with numeric values)
    constexpr bool operator<(const IEC_ENUM_Value& other) const noexcept {
        return static_cast<int>(value_) < static_cast<int>(other.value_);
    }
    
    constexpr bool operator<=(const IEC_ENUM_Value& other) const noexcept {
        return static_cast<int>(value_) <= static_cast<int>(other.value_);
    }
    
    constexpr bool operator>(const IEC_ENUM_Value& other) const noexcept {
        return static_cast<int>(value_) > static_cast<int>(other.value_);
    }
    
    constexpr bool operator>=(const IEC_ENUM_Value& other) const noexcept {
        return static_cast<int>(value_) >= static_cast<int>(other.value_);
    }
    
    // Convert to integer (for serialization, debugging)
    constexpr int to_int() const noexcept {
        return static_cast<int>(value_);
    }
};

/**
 * IEC enumeration variable with forcing support.
 * Wraps IEC_ENUM_Value in IECVar for debugging capabilities.
 *
 * @tparam EnumType The underlying C++ enum class type
 */
template<typename EnumType>
class IEC_ENUM_Var {
public:
    using value_type = IEC_ENUM_Value<EnumType>;
    using enum_type = EnumType;
    
private:
    value_type value_;
    bool forced_;
    value_type forced_value_;
    
public:
    IEC_ENUM_Var() noexcept : value_{}, forced_{false}, forced_value_{} {}

    // Non-explicit so raw `EnumType` values can implicitly convert at call
    // sites — matches the implicit `IECVar(T v)` constructor for elementary
    // types. Without this, codegen would have to wrap every raw enum
    // literal at the call site, since enum-typed variables are now
    // declared as `IEC_<name>` (= IEC_ENUM_Var<EnumType>).
    IEC_ENUM_Var(EnumType val) noexcept
        : value_{val}, forced_{false}, forced_value_{} {}

    IEC_ENUM_Var(value_type val) noexcept
        : value_{val}, forced_{false}, forced_value_{} {}
    
    // Same contract as IECVar, which debug_dispatch.hpp's force_impl/read_impl
    // reach this class through: a fresh instance starts unforced, and assigning
    // FROM another goes through set() so the destination's force survives. A
    // memberwise copy would carry the source's force state across and silently
    // unforce what the debugger is holding, every scan cycle.
    IEC_ENUM_Var(const IEC_ENUM_Var& other) noexcept
        : value_{other.get()}, forced_{false}, forced_value_{} {}
    IEC_ENUM_Var(IEC_ENUM_Var&& other) noexcept
        : value_{other.get()}, forced_{false}, forced_value_{} {}
    IEC_ENUM_Var& operator=(const IEC_ENUM_Var& other) noexcept {
        set(other.get());
        return *this;
    }
    IEC_ENUM_Var& operator=(IEC_ENUM_Var&& other) noexcept {
        set(other.get());
        return *this;
    }
    
    // Get current value (returns forced value if forced)
    value_type get() const noexcept {
        return forced_ ? forced_value_ : value_;
    }
    
    // Ignored while forced, so a force stays authoritative against the
    // program's own writes — the same guard IECVar::set carries.
    void set(value_type v) noexcept {
        if (!forced_) { value_ = v; }
    }
    
    void set(EnumType v) noexcept {
        if (!forced_) { value_ = v; }
    }
    
    /**
     * The payload, for a reader outside the class.
     *
     * Same contract as `IECVar::raw_ptr()`: `force()` mirrors into the raw
     * slot, so what this addresses is the forced value while a force stands.
     * A generic argument's descriptor is filled from here.
     */
    value_type* raw_ptr() noexcept { return &value_; }
    const value_type* raw_ptr() const noexcept { return &value_; }

    // Get underlying value (ignoring forcing)
    value_type get_underlying() const noexcept {
        return value_;
    }
    
    // The raw value follows the force, so external readers reaching the
    // storage directly — a driver, or an ANY descriptor's pvalue — see the
    // forced value too. IECVar::force does the same.
    void force(value_type v) noexcept {
        forced_ = true;
        forced_value_ = v;
        value_ = v;
    }
    
    void force(EnumType v) noexcept {
        forced_ = true;
        forced_value_ = v;
        value_ = v;
    }
    
    // Remove forcing
    void unforce() noexcept {
        forced_ = false;
    }
    
    // Check if forced
    bool is_forced() const noexcept {
        return forced_;
    }
    
    // Get forced value
    value_type get_forced_value() const noexcept {
        return forced_value_;
    }
    
    // Implicit conversion to value_type
    operator value_type() const noexcept {
        return get();
    }
    
    // Implicit conversion to enum_type
    operator EnumType() const noexcept {
        return get().get();
    }
    
    // Assignment operators
    IEC_ENUM_Var& operator=(value_type v) noexcept {
        set(v);
        return *this;
    }
    
    IEC_ENUM_Var& operator=(EnumType v) noexcept {
        set(v);
        return *this;
    }
    
    // Comparison operators
    bool operator==(const IEC_ENUM_Var& other) const noexcept {
        return get() == other.get();
    }
    
    bool operator!=(const IEC_ENUM_Var& other) const noexcept {
        return get() != other.get();
    }
    
    bool operator==(EnumType val) const noexcept {
        return get() == val;
    }
    
    bool operator!=(EnumType val) const noexcept {
        return get() != val;
    }
};

/**
 * Convenience alias for IEC enumeration with forcing support.
 * Usage: IEC_ENUM<MyEnumClass> myVar;
 */
template<typename EnumType>
using IEC_ENUM = IEC_ENUM_Var<EnumType>;

// =============================================================================
// Enumeration traits — which enumeration an operand belongs to
// =============================================================================
//
// IEC 61131-3 Ed 3 §6.6.2.5.14 Table 38 lets SEL, MUX, EQ and NE be applied to
// inputs of an enumerated data type. Those four and no others: an enumeration
// has no defined order, so GT/GE/LT/LE, MIN/MAX and LIMIT are NOT in the table
// and must keep failing to compile. Nor is there a standard conversion to an
// integer — TO_INT takes ANY_ELEMENTARY (Table 33), and §6.4.3 rule 3 puts an
// enumeration in ANY_DERIVED, which is a sibling of ANY_ELEMENTARY, not a
// member of it.
//
// An operand reaches a comparison in one of three spellings, so all three have
// to be recognised: a variable (`IEC_ENUM_Var<E>`), the value a variable
// converts to (`IEC_ENUM_Value<E>`), and a literal, which codegen emits as the
// bare scoped enum `E`.

/** The enumeration `T` belongs to, or no `type` member if it is not one. */
template<typename T, typename = void>
struct iec_enum_of {};

template<typename E>
struct iec_enum_of<IEC_ENUM_Var<E>, void> { using type = E; };

template<typename E>
struct iec_enum_of<IEC_ENUM_Value<E>, void> { using type = E; };

template<typename E>
struct iec_enum_of<E, std::enable_if_t<std::is_enum<E>::value>> { using type = E; };

template<typename T>
using iec_enum_of_t = typename iec_enum_of<T>::type;

// Distinct from iec_traits.hpp's `is_iec_enum`, which answers "is this one of
// the enumeration wrapper classes" and deliberately excludes the bare scoped
// enum. A comparison OPERAND can be the bare enum — that is what codegen emits
// for a literal like `GOOD` — so this predicate is the wider one.
template<typename T, typename = void>
struct is_iec_enum_operand : std::false_type {};

template<typename T>
struct is_iec_enum_operand<T, std::void_t<typename iec_enum_of<T>::type>> : std::true_type {};

template<typename T>
constexpr bool is_iec_enum_operand_v = is_iec_enum_operand<T>::value;

/** Two operands of the SAME enumeration.
 *
 *  Same, not merely both enumerations: §6.4.4.2 says "Different enumerated data
 *  types may use the same identifiers for enumerated values", so comparing
 *  across two of them would compare names that only look alike. */
//  Written as a specialised struct rather than one `&&` expression on purpose.
//  `&&` does not short-circuit at the type level: naming `iec_enum_of_t<A>`
//  beside the test for whether A IS an enumeration instantiates it either way,
//  and for a non-enumeration that is a HARD error, not a substitution failure.
//  It would take every EQ on two plain numbers down with it.
template<typename A, typename B, typename = void>
struct is_same_iec_enum : std::false_type {};

template<typename A, typename B>
struct is_same_iec_enum<A, B,
    std::enable_if_t<is_iec_enum_operand_v<std::decay_t<A>> &&
                     is_iec_enum_operand_v<std::decay_t<B>>>>
    : std::is_same<iec_enum_of_t<std::decay_t<A>>, iec_enum_of_t<std::decay_t<B>>> {};

template<typename A, typename B>
constexpr bool is_same_iec_enum_v = is_same_iec_enum<A, B>::value;

/** The enumerator itself, whichever of the three spellings arrived. */
template<typename T>
constexpr iec_enum_of_t<std::decay_t<T>> iec_enum_value(const T& v) noexcept {
    return static_cast<iec_enum_of_t<std::decay_t<T>>>(v);
}

#ifndef __AVR__
// Stream output for IEC_ENUM_Var — outputs underlying integer value
template<typename EnumType>
inline std::ostream& operator<<(std::ostream& os, const IEC_ENUM_Var<EnumType>& v) {
    return os << static_cast<typename std::underlying_type<EnumType>::type>(
        static_cast<EnumType>(v));
}
#endif

/*
 * Example generated enumeration:
 *
 * ST Source:
 *   TYPE TrafficLight : (RED, YELLOW, GREEN); END_TYPE
 *
 * Generated C++:
 *   enum class TrafficLight : int16_t {
 *       RED = 0,
 *       YELLOW = 1,
 *       GREEN = 2
 *   };
 *   using TrafficLight_Value = IEC_ENUM_Value<TrafficLight>;
 *   using TrafficLight_Var = IEC_ENUM_Var<TrafficLight>;
 *
 * Usage:
 *   TrafficLight_Var light;
 *   light = TrafficLight::RED;
 *   
 *   if (light == TrafficLight::RED) {
 *       // Handle red light
 *   }
 *   
 *   // Force for debugging
 *   light.force(TrafficLight::GREEN);
 *   light = TrafficLight::RED;  // Ignored
 *   assert(light == TrafficLight::GREEN);
 */

/*
 * Example typed enumeration (IEC v3):
 *
 * ST Source:
 *   TYPE Status : INT (IDLE := 0, RUNNING := 1, ERROR := -1); END_TYPE
 *
 * Generated C++:
 *   enum class Status : int16_t {
 *       IDLE = 0,
 *       RUNNING = 1,
 *       ERROR = -1
 *   };
 *   using Status_Value = IEC_ENUM_Value<Status>;
 *   using Status_Var = IEC_ENUM_Var<Status>;
 */


/**
 * `SIZEOF` on an enumeration — the value, not the wrapper.
 *
 * Without this it falls to the generic `IEC_SIZEOF(const T&)` and reports the
 * whole wrapper, forced state included — twelve bytes rather than the width of
 * the enumeration's own base type. Same shape as the STRING and
 * variable-length-array overloads, and for the same reason.
 *
 * Declared here rather than beside those: `iec_std_lib.hpp` includes this
 * header, so the dependency only runs one way.
 */
template <typename EnumType>
inline uint32_t IEC_SIZEOF(const IEC_ENUM_Var<EnumType>&) noexcept {
    return static_cast<uint32_t>(sizeof(IEC_ENUM_Value<EnumType>));
}

}  // namespace strucpp
