/**
 * STruC++ Code Generator Tests
 *
 * Tests for the C++ code generation functionality.
 */

import { describe, it, expect } from 'vitest';
import { CodeGenerator, defaultCodeGenOptions } from '../../src/backend/codegen.js';
import { SymbolTables } from '../../src/semantic/symbol-table.js';
import { createCompilationUnit } from '../../src/frontend/ast.js';

describe('CodeGenerator', () => {
  describe('defaultCodeGenOptions', () => {
    it('should have sensible defaults', () => {
      expect(defaultCodeGenOptions.lineDirectives).toBe(false);
      expect(defaultCodeGenOptions.sourceComments).toBe(true);
      expect(defaultCodeGenOptions.indent).toBe('    ');
      expect(defaultCodeGenOptions.lineEnding).toBe('\n');
    });
  });

  describe('CodeGenerator', () => {
    let generator: CodeGenerator;
    let symbolTables: SymbolTables;

    beforeEach(() => {
      symbolTables = new SymbolTables();
      generator = new CodeGenerator(symbolTables);
    });

    describe('generate', () => {
      it('should generate code for empty compilation unit', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toBeDefined();
        expect(result.headerCode).toBeDefined();
        expect(result.lineMap).toBeDefined();
      });

      it('should include header guard in header', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.headerCode).toContain('#pragma once');
      });

      it('should include runtime includes in header', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.headerCode).toContain('#include "iec_types.hpp"');
        expect(result.headerCode).toContain('#include "iec_std_lib.hpp"');
      });

      it('should include generated header in implementation', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toContain('#include "generated.hpp"');
      });

      it('should include generation comment', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toContain('Generated by STruC++');
        expect(result.headerCode).toContain('Generated by STruC++');
      });

      it('should #undef macros that collide with IEC identifiers', () => {
        // Each platform's standard headers steal short IEC-style names
        // for their own purposes, and macros expand before namespace
        // resolution — so a struct field like `IEC_REAL SP;` becomes
        // `IEC_REAL (*(volatile uint8_t *)(0x3D));` once <avr/io.h> has
        // had its way. The generated header proactively undefs the
        // worst offenders; this test pins the list so a new conflict
        // (or a regression that drops one) surfaces here.
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        // OVERFLOW: math.h on macOS / glibc.
        expect(result.headerCode).toContain('#undef OVERFLOW');
        // SP: <avr/io.h> Stack Pointer macro — collides with PID's
        // setpoint and any user variable named SP.
        expect(result.headerCode).toContain('#undef SP');

        // Both must sit AFTER the runtime includes (otherwise the
        // includes themselves can re-`#define` them) and BEFORE the
        // namespace open (so they cover every emitted struct).
        const headerLines = result.headerCode.split('\n');
        const lastInclude = headerLines.findLastIndex((l) =>
          l.startsWith('#include'),
        );
        const namespaceOpen = headerLines.findIndex((l) =>
          l.startsWith('namespace '),
        );
        const undefSpLine = headerLines.findIndex((l) => l === '#undef SP');
        expect(undefSpLine).toBeGreaterThan(lastInclude);
        expect(undefSpLine).toBeLessThan(namespaceOpen);
      });
    });
  });
});
