/**
 * STruC++ Code Generator Tests
 *
 * Tests for the C++ code generation functionality.
 */

import { describe, it, expect, beforeEach } from "vitest";
import {
  CodeGenerator,
  defaultCodeGenOptions,
} from "../../src/backend/codegen.js";
import { SymbolTables } from "../../src/semantic/symbol-table.js";
import { createCompilationUnit } from "../../src/frontend/ast.js";

describe("CodeGenerator", () => {
  describe("defaultCodeGenOptions", () => {
    it("should have sensible defaults", () => {
      expect(defaultCodeGenOptions.lineDirectives).toBe(false);
      expect(defaultCodeGenOptions.sourceComments).toBe(true);
      expect(defaultCodeGenOptions.indent).toBe("    ");
      expect(defaultCodeGenOptions.lineEnding).toBe("\n");
    });
  });

  describe("CodeGenerator", () => {
    let generator: CodeGenerator;
    let symbolTables: SymbolTables;

    beforeEach(() => {
      symbolTables = new SymbolTables();
      generator = new CodeGenerator(symbolTables);
    });

    describe("generate", () => {
      it("should generate code for empty compilation unit", () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toBeDefined();
        expect(result.headerCode).toBeDefined();
        expect(result.lineMap).toBeDefined();
      });

      it("should include header guard in header", () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.headerCode).toContain("#pragma once");
      });

      it("should include runtime includes in header", () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.headerCode).toContain('#include "iec_types.hpp"');
        expect(result.headerCode).toContain('#include "iec_std_lib.hpp"');
      });

      it("should include generated header in implementation", () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toContain('#include "generated.hpp"');
      });

      it("should include generation comment", () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toContain("Generated by STruC++");
        expect(result.headerCode).toContain("Generated by STruC++");
      });
    });
  });
});
