/**
 * STruC++ Code Generator Tests
 *
 * Tests for the C++ code generation functionality.
 */

import { describe, it, expect } from 'vitest';
import { CodeGenerator, defaultCodeGenOptions } from '../../src/backend/codegen.js';
import { SymbolTables } from '../../src/semantic/symbol-table.js';
import { createCompilationUnit } from '../../src/frontend/ast.js';

describe('CodeGenerator', () => {
  describe('defaultCodeGenOptions', () => {
    it('should have sensible defaults', () => {
      expect(defaultCodeGenOptions.lineDirectives).toBe(false);
      expect(defaultCodeGenOptions.sourceComments).toBe(true);
      expect(defaultCodeGenOptions.indent).toBe('    ');
      expect(defaultCodeGenOptions.lineEnding).toBe('\n');
    });
  });

  describe('CodeGenerator', () => {
    let generator: CodeGenerator;
    let symbolTables: SymbolTables;

    beforeEach(() => {
      symbolTables = new SymbolTables();
      generator = new CodeGenerator(symbolTables);
    });

    describe('generate', () => {
      it('should generate code for empty compilation unit', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toBeDefined();
        expect(result.headerCode).toBeDefined();
        expect(result.lineMap).toBeDefined();
      });

      it('should include header guard in header', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.headerCode).toContain('#pragma once');
      });

      it('should include runtime includes in header', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.headerCode).toContain('#include "iec_types.hpp"');
        expect(result.headerCode).toContain('#include "iec_std_lib.hpp"');
      });

      it('should include generated header in implementation', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toContain('#include "generated.hpp"');
      });

      it('should include generation comment', () => {
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.cppCode).toContain('Generated by STruC++');
        expect(result.headerCode).toContain('Generated by STruC++');
      });

      it('should #undef OVERFLOW to avoid <math.h> macro collisions', () => {
        // `<cmath>` is pulled into every TU via iec_std_lib.hpp, and on
        // both glibc/macOS and avr-libc `<math.h>` defines OVERFLOW as
        // a legacy SVID numeric-error constant. Without this undef, any
        // OSCAT FB struct field named OVERFLOW would get token-replaced
        // before the C++ parser sees it. Pin the line + placement so a
        // regression that drops or relocates it surfaces here.
        //
        // (The companion `#undef SP` for <avr/io.h> was retired once
        // the Arduino glue split moved `generated.hpp` out of any TU
        // that pulls in avr/io.h — no current TU defines `SP` as a
        // macro before parsing the generated header.)
        const ast = createCompilationUnit();
        const result = generator.generate(ast);

        expect(result.headerCode).toContain('#undef OVERFLOW');

        // Must sit AFTER the runtime includes (so the includes can't
        // re-define OVERFLOW after we drop it) and BEFORE the
        // namespace open (so it covers every emitted struct).
        const headerLines = result.headerCode.split('\n');
        const lastInclude = headerLines.findLastIndex((l) =>
          l.startsWith('#include'),
        );
        const namespaceOpen = headerLines.findIndex((l) =>
          l.startsWith('namespace '),
        );
        const undefLine = headerLines.findIndex(
          (l) => l === '#undef OVERFLOW',
        );
        expect(undefLine).toBeGreaterThan(lastInclude);
        expect(undefLine).toBeLessThan(namespaceOpen);
      });
    });
  });
});
